<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Create streams}
-->

## Create streams
```{r packages, results='hide', message=FALSE}
library('clrng')
setContext(grep("gpu", listContexts()$device_type)[1])
```




```{r streams, eval=TRUE}
## check gpu information
gpuR::gpuInfo()

## create 4 streams on CPU as R matrix
a1 <- createStreamsCpu(n=4)

## Important: streams are of type integer in R
typeof(a1) 

## Attention: when converting streams from CPU to GPU, should set type = "integer", or leave it as default `NULL' as below
t(as.matrix(vclMatrix(a1)))
t(as.matrix(2*vclMatrix(a1)))
t(as.matrix(2*vclMatrix(a1, type="integer"))) 

## setting streams as "double" or other type can cause problems, see the following 
t(as.matrix(2*vclMatrix(a1, type="double"))) 
t(as.matrix(vclMatrix(2*a1)))

## save the created streams as .rds object on CPU 
#saveRDS(as.matrix(createStreamsCpu(n = 4)), "myStreams.rds")

## load saved streams
#streams_saved <- vclMatrix(readRDS("myStreams.rds"))
```






