<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Fisher test simulation}
-->

`https://github.com/clMathLibraries/clRNG`


## Fisher test simulation
```{r packages, results='hide'}
library("clrng")
setContext(grep("gpu", listContexts()$device_type)[1])
```

```{r memoryAvailable, echo=TRUE, results='hide'}
## get current device name
gpuInfo()$deviceName
```


## Example
This table is small in dimension and size of values, doesn't really need a simulation. We do the simulation on GPU just for demonstration and test.
See more tests on real data examples on section 4 of the paper "Ruoyong Xu, Patrick Brown, Pierre L’Ecuyer (2021). A tool set for random number generation on GPUs in R."
```{r  teaTasting, eval=T}
TeaTasting <-matrix(c(3, 1, 1, 3),nrow=2)
TeaTasting

## using R's fisher.test()
fisher.test(TeaTasting)$p.value
```

```{r teaTasting on GPU, eval=T}
## using clrng's fisher.sim()

## check the size of work items and GPU precision type at the moment
getOption('clrng.Nglobal')
getOption('clrng.type')

## convert the data table to be on GPU
TeaTastingGpu<-gpuR::vclMatrix(TeaTasting,type="integer")

## choose the size of Nglobal and create 16*64 streams
options(clrng.Nglobal=c(16,64))
streams <- gpuR::vclMatrix(clrng::createStreamsCpu())

## perform 100000 fisher's simulation on GPU and return all test statistics
result<-clrng::fisher.sim(TeaTastingGpu, N=1e5, streams=streams,returnStatistics=TRUE)
print(result)

## show some simulation results
result$threshold
as.vector(result$sim)[10:20]
length(result$sim)
```









